### ISSUE TITLE
[bug] running plain wskdebug 1.2.0 fails with UnhandledPromiseRejectionWarning in y18n

### ISSUE THREAD

**Issue by alexkli** [apache/openwhisk-wskdebug#17]
Seen on node 10, 12 and 13.

```
> npm install -g @openwhisk/wskdebug
> wskdebug
(node:120) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at Y18N.__n (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/y18n/index.js:155:12)
    at Object.positionalCount (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/yargs/lib/validation.js:64:9)
    at populatePositionals (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/yargs/lib/command.js:319:16)
    at Object.runCommand (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/yargs/lib/command.js:218:23)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/yargs/yargs.js:1173:35)
    at Object.parse (/usr/local/lib/node_modules/@openwhisk/wskdebug/node_modules/yargs/yargs.js:618:25)
    at wskdebug (/usr/local/lib/node_modules/@openwhisk/wskdebug/index.js:291:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/@openwhisk/wskdebug/wskdebug.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
(node:120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alexkli** [comment]
Problem is this line: https://github.com/apache/openwhisk-wskdebug/blob/5f0b1c9ce72efcbfe32a1cb7ce4e1731cd7241b2/index.js#L217

One has to provide an object with "one" and "other" keys now: https://github.com/yargs/yargs/issues/913#issuecomment-315643331

Was probably introduced in yargs between `13.x` and current `15.3.0`, which we updated recently.

Only affects `wskdebug`.

`wskdebug -h`, `wskdebug --version` and `wskdebug <action>` work.
